# Generated by Django 4.0.4 on 2022-05-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_new', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='update_at1',
            field=models.EmailField(default='', max_length=254, verbose_name='Email'),
        ),
    ]
