# Generated by Django 4.0.4 on 2022-05-18 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_new', '0002_note_update_at1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='update_at1',
        ),
    ]
