# Generated by Django 4.0.4 on 2022-05-20 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_new', '0003_remove_note_update_at1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
    ]
